# Generated by Django 3.2.11 on 2025-07-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
