# Generated by Django 4.0.3 on 2023-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=300)),
                ('message', models.TextField(max_length=2500)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Contact',
                'db_table': 'Contact',
            },
        ),
    ]
