# Generated by Django 3.2.11 on 2024-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240927_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
